# Generated by Django 4.2.24 on 2026-06-14 05:28

from django.db import migrations
import djangoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", djangoapp.models.UserManager()),
            ],
        ),
    ]
